Levelup
skillsreactor/rpg-learning-example pull request #5
Opened 2020-12-19 16:01 UTC by Maniac-i

resolving the level up issue.

2020-12-20 01:58 UTC, skillsreactor commented
Thanks for the pull request, @Maniac-i! Reviewing now. You can reference issues in a pull request by using the `#` character and then entering the issue number. When you first enter `#` a suggestion dialog will show to help reference the right issue.

For this PR, we could say:  resolves #3

2020-12-20 02:36 UTC, skillsreactor requested changes
I want to look at the experience gain functions. I think the growth of needed experience might be too steep!

2020-12-20 02:36 UTC, skillsreactor commented on actions.js
>      const gold = health + damage;
Let's make an experience variable here that is equal to the enemies health. We can then use this later when the enemy is defeated.

2020-12-20 02:36 UTC, skillsreactor commented on actions.js
> +        character.gainXP();
Let's pass in the new experience variable here that we've defined above.

2020-12-20 02:36 UTC, skillsreactor commented on Character.js
> +Character.prototype.gainXP = function() {
Modify this method to include an experience parameter.

2020-12-20 02:36 UTC, skillsreactor commented on Character.js
> +    const multiplier = Math.floor(1 + this.level/10);
I think we can make this more linear, and remove the Math.floor. That way we don't have such steep increases between 9-10 and 19-20. Also, let's wrap this in a call to `Math.min` and use the smaller of the calculated modifier and our hard-coded 2.

2020-12-20 02:36 UTC, skillsreactor commented on Character.js
> +    const maxXpGain = Math.floor(Math.random() * 10 + 21) * 2;
Let's simplify this by using the experience argument that will be passed in and multiplying by the modifier.

2020-12-20 02:36 UTC, skillsreactor commented on actions.js
> +    character.xp += 10;
We should update this to use our characters gainXp method.

2020-12-20 02:55 UTC, skillsreactor requested changes

2020-12-20 02:55 UTC, skillsreactor commented on Character.js
> +    console.log(`Reach the next level at ${this.nextLevelAt} XP!`);
Let's let the player know here that they've leveled up and what level they now are!

2020-12-20 02:55 UTC, skillsreactor commented
I am ok with the level curve function for now, but we may want to revisit later because it's a bit steep!

2020-12-20 03:52 UTC, skillsreactor requested changes

2020-12-20 03:52 UTC, skillsreactor commented on Character.js
> +    console.log(`Reach the next level at ${this.nextLevelAt} XP!`);
We also need to increase their attack and health here.

2020-12-22 19:47 UTC, Maniac-i commented on actions.js
> +    character.xp += 10;
I think it would be best just to remove the xp gain from resting all together.  You shouldn't receive xp from that action.

2020-12-22 19:51 UTC, skillsreactor commented on actions.js
> +    character.xp += 10;
Agreed! Let's remove it.

2020-12-22 20:44 UTC, Maniac-i commented on actions.js
>      const gold = health + damage;
this was update with `const xp = health;`

2020-12-22 20:45 UTC, Maniac-i commented on actions.js
> +        character.gainXP();
this was updated with `character.gainXP(xp);`

2020-12-22 20:46 UTC, Maniac-i commented on Character.js
> +Character.prototype.gainXP = function() {
this was updated to include an experience parameter `Character.prototype.gainXP = function(xp) {`

2020-12-22 20:48 UTC, Maniac-i commented on Character.js
> +    const multiplier = Math.floor(1 + this.level/10);
updated to simplify the code. The hardcoded multiplier turns out to be 3, not 2.

` const multiplier = Math.min(1 + this.level/10, 3);`
    `const xpGained = ~~(xp * multiplier);`
        `this.xp += xpGained;`

2020-12-22 20:49 UTC, Maniac-i commented on Character.js
> +    const maxXpGain = Math.floor(Math.random() * 10 + 21) * 2;
see above comment.

2020-12-22 20:51 UTC, Maniac-i commented on Character.js
> +    console.log(`Reach the next level at ${this.nextLevelAt} XP!`);
increases health and attack. A conditional was used to restore the characters health back it its original health + 20 per level when they level up.

2020-12-23 03:37 UTC, skillsreactor requested changes
Looking great @Maniac-i, a few more changes and we'll get this pulled in!

2020-12-23 03:37 UTC, skillsreactor commented on Character.js
> +    console.log(`Reach the next level at ${this.nextLevelAt} XP!`);
Looks good! I think we need to make an issue to add a `maxHealth` to our character classes so that we don't allow them to rest far above the health that their class should have, and to also increase it on level up. This is good for now.

2020-12-23 03:37 UTC, skillsreactor commented on actions.js
> +    const enemy = { damage, health, gold, };
From a style perspective, I think it makes sense to associate the xp with the enemy by making it a property, but this is also reasonable.

2020-12-23 03:37 UTC, skillsreactor commented on actions.js
> +    console.log("You have gained 25 health for 10 gold and 10 XP.");
Also remove the reference here in this string.

2020-12-23 03:39 UTC, skillsreactor commented on actions.js
> +
We can remove this entire section, we're not going to need to check for level up, and the text is duplicated below.

2020-12-23 03:52 UTC, skillsreactor commented on actions.js
> +        character.gainXP();
Not seeing the change here on the latest commit.

2020-12-28 21:22 UTC, Maniac-i commented on actions.js
> +    console.log("You have gained 25 health for 10 gold and 10 XP.");
complete.

2020-12-28 21:22 UTC, Maniac-i commented on actions.js
> +
complete.

2020-12-29 00:37 UTC, skillsreactor approved these changes
LGTM!

2020-12-29 00:38 UTC, merged